name: build-mac-universal-pd-external

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  mac-universal:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Pure Data headers
        run: |
          git clone --depth 1 https://github.com/pure-data/pure-data pd-src
          test -f pd-src/src/m_pd.h

      - name: Build universal .pd_darwin (arm64 + x86_64)
        run: |
          clang -O3 -DPD -std=c99 \
            -arch x86_64 -arch arm64 \
            -mmacosx-version-min=10.13 \
            -I"$GITHUB_WORKSPACE/pd-src/src" \
            -bundle -undefined dynamic_lookup \
            exciter_juicy~.c \
            -o exciter_juicy~.pd_darwin
          lipo -info exciter_juicy~.pd_darwin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: exciter_juicy-mac-universal
          path: exciter_juicy~.pd_darwin
