name: build-pd-external

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build macOS .pd_darwin
        run: |
          clang -O3 -DPD -std=c99 -fPIC -shared \
            -I/Applications/Pd.app/Contents/Resources/src \
            -o exciter_juicy~.pd_darwin exciter_juicy~.c
      - uses: actions/upload-artifact@v4
        with:
          name: macos-pd-darwin
          path: exciter_juicy~.pd_darwin

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y puredata-dev
      - name: Build Linux .pd_linux
        run: |
          clang -O3 -DPD -std=c99 -fPIC -shared \
            -I/usr/include/pd \
            -o exciter_juicy~.pd_linux exciter_juicy~.c -lm
      - uses: actions/upload-artifact@v4
        with:
          name: linux-pd-linux
          path: exciter_juicy~.pd_linux
